title: 2025 Frugal AI Challenge
nav_title: Frugal AI Challenge <br><small><span class="hide-very-narrow">co-located with the 2025 </span> AI Action Summit</small>

event_date: 11 February 2025
registration_opens_date: January 6 2025
registration_closes_date: January 31 2025

author: Frugal AI Challenge Organizing Committee
mailbox_address: frugalaichallenge@gmail.com

description:
  The goal of the Frugal AI Challenge is to encourage both academic and industry actors to keep efficiency in mind when deploying AI models. 
  By tracking both energy consumption and performance for different Aasks, we can incentivize frugality in AI deployment while addressing real-world challenges.


url: "https://frugal-ai-challenge.github.io"
github_repo: frugal-ai-challenge

theme: minima

# The actual visibility of the nav bar links is influenced by the event_status
# and registration_status flags below
header_pages:
  - about.md
  - tasks.md
  - resources.md
  - registration.md


# Event status
#   soon = event is yet to happen
#    now = event is currently happening
#   over = event has happened
#  (demo = show all pages to demonstrate the template)
event_status: soon

# Open and close the registration form
#   soon = Registration has not yet opened
#   open = Registration form is open
# closed = Registration form is now closed
#  (demo = show all pages to demonstrate the template)
registration_status: soon

# Remove ".html" from default permalinks
permalink: pretty

# (See default layout below)
collections:
  projects:
    output: true
    permalink: /:collection/:name/

# Social media links
# (See default layout below)
twitter:
  card: summary_large_image

defaults:
  - scope:
      path: ""
    values:
      image: /assets/advert.png
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

# Simplify tables of contents
kramdown:
  toc_levels: "2,3"
